component extends=ring.core {

  // (require '[ring.util.response :as resp])
  resp = new ring.util.response();

  handler = function( req ) {
    return resp.response(
      "<h1>Hello</h1>" &
      "<p>Generated by the handler!</p>"
    );
  };

}
